### ISSUE TITLE
Unused arguments in crosstalk::filter_slider

### ISSUE THREAD

**Issue by ridwan-shaikh** [sigven/cpsr#19] opened 2019-10-11 15:55 UTC
Hi Sigven,

I should have started the other issue with a thanks for the package btw! I am currently testing out CPSR for germline reporting and tiering as I already have PCGR in use for somatic reporting. So a huge thank you.

Anyway found another bug (I am not sure if it just because I am using the non-dockerised version on our cluster, so some packages may be out of date)

`Error in crosstalk::filter_slider("CLINVAR_REVIEW_STATUS_STARS", "ClinVar review status stars",  : 
  unused arguments (min = 0, max = 4)
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>
Execution halted
`

I have just hashed out the min = 0 and max = 4 in the lines of predisposition_class1_5.Rmd and the resulting html report slider looks to be functioning correctly.

![Screenshot 2019-10-11 at 16 52 54](https://user-images.githubusercontent.com/48447625/66666017-a5341d80-ec47-11e9-94b5-f360190be109.png)

**Comment by sigven** [comment] 2019-10-11 15:59
Ah thanks a lot for reporting! In order for me to reproduce the bug, would it be possible for you to share the variant set (VCF) with me somehow? And build (grch37/grch38) and config file?

best,
Sigve

**Comment by ridwan-shaikh** [comment] 2019-10-11 16:00
Hi Sigven,

This was on your example vcf in the CPSR-0.5.0 build

**Comment by sigven** [comment] 2019-10-11 16:02
Got it. Will test later! Thanks again.

best,
Sigve

**Comment by ridwan-shaikh** [comment] 2019-10-11 16:06
Just looking at the help function for filter_slider, it looks like the argument 'min', 'max' does not exist. Maybe dragRange would work:

`crosstalk::filter_slider("CLINVAR_REVIEW_STATUS_STARS", "ClinVar review status stars", variants_class5_1, ~CLINVAR_REVIEW_STATUS_STARS, ticks = T, dragRange = range(CLINVAR_REVIEW_STARS)) #not tested`

regards,
Ridwan

**Comment by sigven** [comment] 2019-10-11 16:29
Hm. A bit strange. Ran the example now, and it work (Dockerized). If you look at the commit comment for the `man` directory  at [https://github.com/rstudio/crosstalk](https://github.com/rstudio/crosstalk), it seems it has been added to the help text also? But that seem to be committed quite long time a go..

Will make a push to dev for you to test on your local installation.

best,
Sigve

**Comment by sigven** [comment] 2019-10-12 06:47
It might be that the `install_no_docker` version (i.e. conda) installs the `crosstalk` package from CRAN (1.0.0) and not the updated version on GitHub (1.0.1). Could that be the reason, @vladsaveliev?

**Comment by ridwan-shaikh** [comment] 2019-10-12 17:15
Yes that looks to be the reason. I just had a look at the packages suggested in a fresh install of the conda environment it say: conda-forge/noarch::r-crosstalk-1.0.0-r35h6115d3f_1002. Curiously, I had an error of the following packages not existing when attempting to run for the first time.

- BSgenome.Hsapiens.UCSC.hg38
- BSgenome.Hsapiens.UCSC.hg19

Sorry I didn't take a screenshot at the time of the error as both packages a clearly listed in the yaml but for some reason are not downloaded/installed in the condo environment.

**Comment by vladsaveliev** [comment] 2019-10-12 23:00
Huh, thanks for the forensics! I will modify the conda recipe to use the GitHub version of `crosstalk`.

Regarding the BSGenome packages, I remember having some issues with them too. I will just install them directly in the recipe from bioconductor instead of using conda versions, that should solve the problem.

**Comment by vladsaveliev** [comment] 2019-10-13 08:23
Hmm, it looks like though [GitHub has 1.0.0](https://github.com/rstudio/crosstalk/blob/master/package.json#L3) as well? 

If PCGR needs some unreleased features, one way would be to build our own package for crosstalk under the pcgr channel. Happy to do that (I think I already did it once for the condarized version, before https://github.com/rstudio/crosstalk/pull/56 was merged)

**Comment by vladsaveliev** [comment] 2019-10-28 22:29
Alright, updated the recipes and pushed pcgr==0.8.3.1 and cpsr==0.5.1.2 into anaconda. This versions use Crosstalk from GitHub which fixes this issue. Also I[m not having the BSGenome errors, but let me know if it happens to you again.

To update:

```
conda install -c pcgr "pcgr>=0.8.3.1" "cpsr>=0.5.1.2"
```

**Comment by ridwan-shaikh** [comment] 2019-10-29 13:03
Hi Vlad,

when attempting to update using:

`conda install -c pcgr "pcgr>=0.8.3.1" "cpsr>=0.5.1.2"`

```shell
$ conda install -c pcgr "pcgr>=0.8.3.1" "cpsr>=0.5.1.2"
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cpsr[version='>=0.5.1.2'] -> r-ggpubr

Current channels:

  - https://conda.anaconda.org/pcgr/linux-64
  - https://conda.anaconda.org/pcgr/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

Does this indicate that conda-forge channel does not exist as a list of channels?

So I installed ggpubr:

```shell
conda install -c conda-forge r-ggpubr
Collecting package metadata: done
Solving environment: done
```

and then tried updating cpsr

```shell
$ conda install -c pcgr "cpsr>=0.5.1.2"
Collecting package metadata: done
Solving environment: failed


UnsatisfiableError: The following specifications were found to be in conflict:
  - cpsr[version='>=0.5.1.2']
Use "conda search <package> --info" to see the dependencies for each package.

$ conda search cpsr --info
Loading channels: done
No match found for: cpsr. Search: *cpsr*
r-icpsrdata 0.4.0 r36h6115d3f_0
-------------------------------
file name   : r-icpsrdata-0.4.0-r36h6115d3f_0.tar.bz2
name        : r-icpsrdata
version     : 0.4.0
build       : r36h6115d3f_0
build number: 0
size        : 428 KB
license     : MIT
subdir      : noarch
url         : https://repo.anaconda.com/pkgs/r/noarch/r-icpsrdata-0.4.0-r36h6115d3f_0.tar.bz2
md5         : 0470d469c698fef23fb71d11e9e0e1d5
timestamp   : 2019-09-12 21:29:34 UTC
dependencies: 
  - r-base >=3.6,<3.7.0a0
  - r-httr
  - r-purrr
  - r-rvest
  - _r-mutex 1.* anacondar_1
```
but cpsr is listed when running `conda list`

**Comment by vladsaveliev** [comment] 2019-10-30 04:55
Ah, sorry @ridwan-shaikh, I already have conda-forge and bioconda in my .condrc and that's why didn't bother adding them into the command line. The correct one should be:

```
conda install -c pcgr -c conda-forge -c bioconda "pcgr>=0.8.3.1" "cpsr>=0.5.1.2"
```

Worked for me, can you try? If it errors with UnsatisfiableError again, can you try installing into a clean env please? (`conda create -n pcgr -c pcgr -c conda-forge -c bioconda "pcgr>=0.8.3.1" "cpsr>=0.5.1.2"`) Just for a clean experiment.

**Comment by ridwan-shaikh** [comment] 2019-10-30 10:34
Hi Vlad,

yes adding the correct channels helps to update to the latest cpsr version.

For testing purposes i tried a fresh install too, to see what crosstalk is added and you're right, cross talk remains at v1.0.0.

**Comment by vladsaveliev** [comment] 2019-10-31 04:57
Sorted it out. Conda details. Turns out I need to update crosstalk in `post-link.sh` script instead of `build.sh`, to make sure it's executed on a host machine. Anyway. Try updating? :)

```
conda install -c pcgr -c conda-forge -c bioconda "pcgr==0.8.3.2" "cpsr==0.5.1.3"
```

**Comment by ridwan-shaikh** [comment] 2019-10-31 14:52
Hi Vlad,

Running the above command results in:

```shell
added / updated specs:
    - cpsr==0.5.1.3
    - pcgr==0.8.3.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpsr-0.5.1.3               |                0          10 KB  pcgr
    ------------------------------------------------------------
                                           Total:          10 KB

The following NEW packages will be INSTALLED:

  cpsr               pcgr/linux-64::cpsr-0.5.1.3-0
  r-ggpubr           conda-forge/noarch::r-ggpubr-0.2.3-r35h6115d3f_0
  r-ggrepel          conda-forge/linux-64::r-ggrepel-0.8.1-r35h0357c0b_1
  r-ggsci            conda-forge/noarch::r-ggsci-2.9-r35h6115d3f_1002
  r-ggsignif         conda-forge/noarch::r-ggsignif-0.6.0-r35h6115d3f_0
  r-polynom          conda-forge/noarch::r-polynom-1.4_0-r35h6115d3f_1
  r-upsetr           conda-forge/noarch::r-upsetr-1.4.0-r35h6115d3f_1

```

and `conda list` results in:

```shell
r-crosstalk               1.0.0           r35h6115d3f_1002    conda-forge
```

Does not look like it has updated crosstalk. To get around it, I have just been installing the github version of crosstalk through R 

`devtools::install_github("https://github.com/rstudio/crosstalk.git")`

**Comment by vladsaveliev** [comment] 2019-11-01 00:40
Ridwan,

`conda list` will show `1.0.0` because `1.0.1` does not exist on conda (and neither on cran - it wasn't released). My change to the `pcgr` package was to actually run `devtools::install_github("https://github.com/rstudio/crosstalk.git")` automatically in the end of the installation. So 1.0.1 should be reflected if you run `R -e "library(crosstalk); sessionInfo();"` (regardless of the conda version). Though if it didn't work for you, I might have screwed something up and need to investigate further. Wondering if you could try installing the package a new env and checking sessionInfo?

Also I'm wondering why did it only updated `cpsr`, but not the `pcgr` package as well. Did you update the packages in 2 steps by any chance?

**Closed** 2019-12-06 14:11 UTC
