### ISSUE TITLE
Variant missed in GRCh38

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/cpsr#15] opened 2019-08-27 11:55 UTC
Hey Sigve,

This APC missense variant (rs459552) is reported as Benign in GRCh37, but missed in GRCh38. Can't figure out why. The Vep pick order doesn't seem to affect this. All fields in the intermediate TSV file seem to be pretty similar...

Attaching the VCFs below:

[rs459552_grch37.vcf.gz](https://github.com/sigven/cpsr/files/3545934/rs459552_grch37.vcf.gz)
[rs459552_grch38.vcf.gz](https://github.com/sigven/cpsr/files/3545935/rs459552_grch38.vcf.gz)

Running as follows:

```
cpsr.py /Users/vsaveliev/tmp/p007/rs459552.vcf.gz pcgr output grch38 0 ~/git/cpsr/cpsr.toml 2016_249_18_SV_P007__CCR180064_SV18T002P007-normal  --docker-uid root --force_overwrite --no_vcf_validate
```

Could you take a look please if you got a moment?

Vlad

**Comment by sigven** [comment] 2019-08-29 10:41
Hey Vlad, 
Sure I'll have a look, just give me a couple of days.  WIll get back to you shortly.

best,
Sigve

**Comment by sigven** [comment] 2019-08-29 20:57
Just ran the variant against VEP 97 (soon for release with PCGR/CPSR), and it seems to produce similar results for both builds. Results [here](https://www.dropbox.com/sh/dcemrsszuc642hg/AACBuGX3Aa6C6g6se8D05ElKa?dl=0)

I remember there was an [existing issue](https://github.com/Ensembl/ensembl-vep/issues/413) with the cache for 96 (for chromosome 5, interestingly). Could be the root of the cause.

best,
Sigve

**Comment by vladsaveliev** [comment] 2019-08-30 02:47
Thanks Sigve! Seems to be working for me with VEP 97.

**Comment by vladsaveliev** [comment] 2019-08-30 23:29
Updated VEP to 97 manually, no luck. I guess I might need the CPSR update as well?

**Comment by sigven** [comment] 2019-08-31 06:22
Yeah, it's on its way. Will try to have it out next week.

best,
Sigve

**Comment by ohofmann** [comment] 2019-09-06 01:31
Thanks so much, Sigve.

**Comment by sigven** [comment] 2019-10-14 13:39
Closing this issue for now. ClinVar is updated, so is VEP (98)

**Closed by sigven** 2019-10-14 13:39 UTC
